### ISSUE TITLE
Just wanted to let you know -O3 in makefile works for me

### ISSUE THREAD

**Issue by Overdrive5** [twistdroach/open-source-search-engine#1]
on makefile lines 90,101 & 105 changed to -O3 compiles and runs for 24 hours without issues.

Thank You!!!

**Comment by twistdroach** [comment]
Cool - I tested it loading about 200k pages + a bunch of search queries on a 16 node cluster and it seemed fine....pushed

**Comment by Overdrive5** [comment]
Cool, I have been testing "-Ofast -mfpmath=sse" and it seems to be working well also.

Optionally, if you know the executable will only reside on the machine it was built on, -"march=native" will optimize it even further.

Also, FYI, I saw someone else recommend "-ftree-vectorize", but I have found that problematic during spidering. https://github.com/gigablast/open-source-search-engine/issues/117

Edit: When I say problematic, I mean lots more errors.

**Comment by twistdroach** [comment]
I'm not surprised - in the CPPFLAGS - the original author has set strict-aliasing=0, disabling aliasing checks...and there are lots of upcasting `char *` (essentially being used as `void *`) to wider types without ensuring proper alignment/aliasing.  If you run with the undefined behavior checker enabled, it will call it out.  All of this will confuse the compiler when it tries to generate code with SSE/AVX/etc.  The alignment issues will probably crash it on arm, though I haven't tried to run this on a raspberry pi yet.  I'd like to eventually get it running on a pi though.  Anyway, as I have time I'll probably dig into this more.
